name: hardcore-no-regen
version: '1.0-SNAPSHOT'
main: com.karotte128.hardcoreNoRegen.HardcoreNoRegen
api-version: '1.21'
load: STARTUP
commands:
  timer:
    description: Challenge Timer
    usage: /timer <start/reset/set seconds>
    permission: eventplugins.admin